---
configure_terminal: false

# Dotfiles
dotfiles_repo: "https://github.com/JDLK7/dotfiles-2.git"
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/workspace/GitHub/dotfiles
dotfiles_files:
  - .aliases.zsh
  - .curl-format
  - .osx
  - .p10k.zsh
  - .vimrc
  - .zshrc

sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - cowsay
  - delve
  - doxygen
  - gettext
  - gh
  - gifsicle
  - git
  - go
  - gpg
  - htop
  - httpie
  - iperf
  - jq
  - libevent
  - mcrypt
  - mrroboto
  - nmap
  - node
  - nvm
  - openssl
  - php
  - pv
  - readline
  - sqlite
  - ssh-copy-id
  - tmux
  - tree
  - watch
  - wget
  - wrk

homebrew_cask_apps:
  - 1password
  - docker
  - iterm2
  - spotify
  - visual-studio-code
  - alfred
  - firefox
  - google-chrome
  - postman
  - font-fira-code
  - ngrok
  - rambox
  - handbrake
