---
# Dotfiles
dotfiles_repo: "https://github.com/JDLK7/dotfiles-2.git"
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/workspace/GitHub/dotfiles
dotfiles_files:
  - .aliases.zsh
  - .curl-format
  - .osx
  - .p10k.zsh
  - .spaceship.zsh
  - .vimrc
  - .zshrc

sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - cowsay
  - delve
  - doxygen
  - gettext
  - gh
  - gifsicle
  - git
  - go
  - gpg
  - htop
  - httpie
  - iperf
  - jq
  - libevent
  - mcrypt
  - nmap
  - node
  - nvm
  - openssl
  - php
  - pv
  - readline
  - spaceship
  - sqlite
  - ssh-copy-id
  - tmux
  - tree
  - watch
  - wget
  - wrk
  - zsh
#  - mrroboto

homebrew_cask_apps:
  - 1password
  - alfred
  - docker
  - firefox
  - font-fira-code
  - font-fontawesome
  - font-hack-nerd-font
  - google-chrome
  - handbrake
  - iterm2
  - ngrok
  - nordvpn
  - postman
  - rambox
  - spotify
  - visual-studio-code
