---
# This configuration is needed to clone the monorepo
- name: Update git config
  git_config:
    scope: global
    name: core.compression
    value: 9

- name: Workspace directory
  file:
    path: "~/workspace/{{ masmovil_org }}"
    state: directory

- name: Clone repos
  git:
    repo: "git@github.com:{{ masmovil_org }}/{{ item }}.git"
    dest: "~/workspace/{{ masmovil_org }}/{{ item }}"
  loop: "{{ masmovil_repos }}"

- name: Link OpenJDK
  become: true
  file:
    src: /usr/local/opt/openjdk@11/libexec/openjdk.jdk
    dest: /Library/Java/JavaVirtualMachines/openjdk-11.jdk
    state: link

- name: Check if ~/.zshrc exists
  stat:
    path: ~/.zshrc
  register: zshrc_stat_result

- name: Check if ~/.bashrc exists
  stat:
    path: ~/.bashrc
  register: bashrc_stat_result

- name: Add configuration to .zshrc
  when: zshrc_stat_result.stat.exists
  blockinfile:
    state: present
    insertafter: EOF
    dest: ~/.zshrc
    marker: "#### {mark} ANSIBLE MANAGED BLOCK ####"
    content: |
      # Java 11
      export PATH="/usr/local/opt/openjdk@11/bin:$PATH"

      # Helm
      export HELM_HOME=$HOME/.helm

      # GCloud SDK
      source "$(brew --prefix)/share/google-cloud-sdk/path.zsh.inc"
      source "$(brew --prefix)/share/google-cloud-sdk/completion.zsh.inc"

- name: Add configuration to .bashrc
  when: bashrc_stat_result.stat.exists
  blockinfile:
    state: present
    insertafter: EOF
    dest: ~/.bashrc
    marker: "#### {mark} ANSIBLE MANAGED BLOCK ####"
    content: |
      # Java 11
      export PATH="/usr/local/opt/openjdk@11/bin:$PATH"

      # Helm
      export HELM_HOME=$HOME/.helm

      # GCloud SDK
      source "$(brew --prefix)/share/google-cloud-sdk/path.bash.inc"

- name: Install GCloud components
  command: "gcloud components install kubectl -q"

- name: GCloud SDK login
  command: gcloud auth login

- name: GCloud login for other applications
  command: gcloud auth application-default login

- name: GCloud token
  command:  gcloud auth application-default print-access-token | helm registry login -u oauth2accesstoken  --password-stdin europe-docker.pkg.dev

- name: GCP clusters credentials
  tags: ["gcp_credentials"]
  command: "gcloud container clusters get-credentials {{ item.name }} --region {{ item.region }} --project {{ item.project }}"
  loop: "{{ masmovil_clusters }}"

- debug:
    msg: You may need to source ~/.bashrc or ~/.zshrc for some commands to work.

# TODO: "helm repo add ..." throws this error -> Error: looks like "<repo_url>" is not a valid chart repository or cannot be reached: failed to fetch <repo_url>/index.yaml : 404 Not Found

# - name: Helm plugins directory
#   file:
#     path: "~/.helm/plugins"
#     state: directory

# - name: Install Helm plugins
#   command: "helm plugin install https://github.com/futuresimple/helm-secrets"

# - pause:
#     prompt: "Make sure you are connected to the VPN. Type 'y' to continue when you are ready"
#   register: is_connected_to_vpn

# - name: Helm repository
#   when: is_connected_to_vpn.user_input == 'y'
#   command: "helm repo add {{ masmovil_org }} {{ masmovil_chart_repo }}"
