---
# This configuration is needed to clone the monorepo
- name: Update git config
  git_config:
    scope: global
    name: core.compression
    value: 9

- name: Workspace directory
  file:
    path: "~/workspace/{{ masmovil_org }}"
    state: directory

- name: Clone repos
  git:
    repo: "git@github.com:{{ masmovil_org }}/{{ item }}.git"
    dest: "~/workspace/{{ masmovil_org }}/{{ item }}"
  loop: "{{ masmovil_repos }}"

- name: GCloud SDK login
  command: gcloud auth login

- name: GCloud login for other applications
  command: gcloud auth application-default login

- name: GCP clusters credentials
  command: "gcloud container clusters get-credentials {{ item.name }} --region {{ item.region }} --project {{ item.project }}"
  loop: "{{ masmovil_clusters }}"
