---    
- name: Fetch oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh

- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: zshrc_path

- name: Creating new zshrc
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
  when: not zshrc_path.stat.exists

- name: Get current user
  command: whoami
  register: user
  changed_when: false
  when: user is undefined

- name: Set Z shell as default shell
  become: true
  user:
    name: "{{ user.stdout }}"
    shell: /bin/zsh

- name: Fetch Spaceship Prompt
  git:
    repo: https://github.com/spaceship-prompt/spaceship-prompt.git
    dest: ~/.oh-my-zsh/custom/themes/spaceship-prompt
    depth: 1

- name: Symlink Spaceship Prompt themes
  file:
    src: ~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme
    state: link

# The profile needs to be imported on iTerm
- name: Copy iTerm profile
  ansible.builtin.copy:
    src: templates/iterm-profile.json
    dest: "{{ personal_workspace }}/iterm-profile.json"
