---
- name: Install apt packages
  ansible.builtin.apt:
    update_cache: yes
    pkg: "{{ apt_packages }}"

- name: Install snap packages
  tags: ['snap']
  community.general.snap:
    name: "{{ item }}"
    channel: "latest/stable"
  with_items: "{{ snap_packages.regular }}"

- name: Install snap classic packages
  tags: ['snap']
  community.general.snap:
    name: "{{ item }}"
    classic: true
    channel: "latest/stable"
  with_items: "{{ snap_packages.classic }}"
